/**
 * Provision Epic OS Stripe product, weekly/monthly/yearly prices, and webhook.
 * Requires STRIPE_SECRET_KEY in env.
 *
 * Usage: npx tsx scripts/setup-stripe.ts
 * Output: bootstrap/secrets/stripe.env (gitignored) — copy vars to Railway dashboard.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import Stripe from "stripe";

const ROOT = dirname(fileURLToPath(new URL("..", import.meta.url)));
const OUT_DIR = join(ROOT, "bootstrap", "secrets");
const OUT_FILE = join(OUT_DIR, "stripe.env");

const site = process.env.NEXT_PUBLIC_SITE_URL ?? process.env.AUTH_URL;
const key = process.env.STRIPE_SECRET_KEY;

if (!key) {
  console.error("Set STRIPE_SECRET_KEY first");
  process.exit(1);
}
if (!site) {
  console.error("Set NEXT_PUBLIC_SITE_URL or AUTH_URL first");
  process.exit(1);
}

const siteUrl = site;
const stripe = new Stripe(key);

const PRICE_SPECS = [
  { amount: 999, interval: "week" as const, lookupKey: "epic_os_weekly", envKey: "STRIPE_PRICE_WEEKLY" },
  { amount: 2999, interval: "month" as const, lookupKey: "epic_os_monthly", envKey: "STRIPE_PRICE_MONTHLY" },
  { amount: 29900, interval: "year" as const, lookupKey: "epic_os_yearly", envKey: "STRIPE_PRICE_YEARLY" },
];

async function findOrCreateProduct() {
  const name = "Epic OS";
  const existing = await stripe.products.search({ query: `name:'${name}'` });
  if (existing.data[0]) return existing.data[0];
  return stripe.products.create({
    name,
    description: "Your personal AI operating system — cloud workspace, apps, deploy tools, and desktop agent",
  });
}

async function findOrCreatePrice(
  productId: string,
  amount: number,
  interval: Stripe.Price.Recurring.Interval,
  lookupKey: string,
) {
  try {
    const prices = await stripe.prices.list({ lookup_keys: [lookupKey], active: true });
    if (prices.data[0]) return prices.data[0];
  } catch {
    /* lookup_keys may not exist on old accounts */
  }
  return stripe.prices.create({
    product: productId,
    currency: "usd",
    unit_amount: amount,
    recurring: { interval },
    lookup_key: lookupKey,
  });
}

const WEBHOOK_EVENTS: Stripe.WebhookEndpointCreateParams.EnabledEvent[] = [
  "checkout.session.completed",
  "customer.subscription.created",
  "customer.subscription.updated",
  "customer.subscription.deleted",
  "invoice.payment_failed",
  "charge.dispute.created",
  "charge.dispute.closed",
  "radar.early_fraud_warning.created",
];

async function ensureWebhook() {
  const url = `${siteUrl.replace(/\/$/, "")}/api/stripe/webhook`;
  const endpoints = await stripe.webhookEndpoints.list({ limit: 20 });
  const found = endpoints.data.find((e) => e.url === url);
  if (found) {
    const merged = [
      ...new Set([...found.enabled_events, ...WEBHOOK_EVENTS]),
    ] as Stripe.WebhookEndpointCreateParams.EnabledEvent[];
    if (merged.length !== found.enabled_events.length) {
      const updated = await stripe.webhookEndpoints.update(found.id, { enabled_events: merged });
      console.log("Webhook updated with fraud/dispute events:", updated.id);
      return { endpoint: updated, created: false as const };
    }
    console.log("Webhook exists:", found.id);
    return { endpoint: found, created: false as const };
  }
  const created = await stripe.webhookEndpoints.create({
    url,
    enabled_events: WEBHOOK_EVENTS,
  });
  return { endpoint: created, created: true as const };
}

function writeEnvFile(lines: string[]) {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, lines.join("\n") + "\n", { mode: 0o600 });
}

async function main() {
  const product = await findOrCreateProduct();
  const prices: { envKey: string; id: string; interval: string }[] = [];

  for (const spec of PRICE_SPECS) {
    const price = await findOrCreatePrice(product.id, spec.amount, spec.interval, spec.lookupKey);
    prices.push({ envKey: spec.envKey, id: price.id, interval: spec.interval });
  }

  const { endpoint: webhook, created: webhookCreated } = await ensureWebhook();

  const envLines = [
    "# Generated by scripts/setup-stripe.ts — DO NOT COMMIT",
    ...prices.map((p) => `${p.envKey}=${p.id}`),
  ];

  if (webhookCreated && "secret" in webhook) {
    envLines.push(`STRIPE_WEBHOOK_SECRET=${(webhook as { secret?: string }).secret}`);
  } else {
    envLines.push("# STRIPE_WEBHOOK_SECRET=<copy from Stripe Dashboard — endpoint already exists>");
  }

  writeEnvFile(envLines);

  console.log("\n=== Stripe provisioning complete ===\n");
  console.log("Epic OS — Weekly $9.99 · Monthly $29.99 · Yearly $299");
  for (const p of prices) console.log(`  ${p.interval}: ${p.id}`);
  console.log(`Vars written to bootstrap/secrets/stripe.env (gitignored)`);
  console.log("Copy those values into Railway — never commit or paste webhook secrets in chat.");
  if (!webhookCreated) {
    console.log("Webhook already existed; signing secret is only shown once at creation.");
  }
  console.log("\nNo free tier — subscribers only. Re-run seed if needed.");
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : "Stripe setup failed");
  process.exit(1);
});